# Site settings
title: Jalen 's Blog
SEOTitle: Jalen的博客 | Jalen 's Blog
header-img: img/home-bg.jpg
email: iwangjiaolong@163.com
description: "关于程序与设计 | Jalen，Software Engineer | 这里是 @Jalen 的个人博客，与你一起发现更大的世界。"
keyword: "Jalen, Jiaolong"
url: "https://blog.jiaolong.space"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     iwangjiaolong
zhihu_username:     wang-jiaolong
github_username:    Wang-Jiaolong
bilibili_username: 239811731
jike_username: DB74F1FC-514A-44A6-B8BE-D09E27C873E6
mysite_url: https://jiaolong.space/
# twitter_username:   Wang-Jiaolong
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1





# Analytics settings
# Baidu Analytics 
ba_track_id: e97d90582c20cf2e3acfe7cab03ec724

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个正在成长的开发者<br>"
sidebar-avatar: /img/me.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 3              # A tag will be featured if the size of it is more than this condition value



collections:
  wikis:
    output: true   

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    # {
    #     title: "乱序（Midare）",
    #     href: "http://mida.re/"
    # },{
    #     title: "Sherry Woo",
    #     href: "https://sherrywoo.me/"
    # },{
    #     title: "Kun Qian",
    #     href: "http://kunq.me"
    # },{
    #     title: "Ebn Zhang",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "JiyinYiyong",
    #     href: "http://tiye.me/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # }
]


gitalk: 
  enable: true 
  owner: Wang-Jiaolong
  repo: blog-comments
  oauth: 
    clientId: b99130a693ed94800a21
    clientSecret: 181e5b5b8543bf81bc22dccba9698ab8683e2edd
  admin: Wang-Jiaolong
